language: c++
# command to install dependencies
before_install:
  - sudo add-apt-repository -y ppa:octave/stable
  - sudo apt-get update -qq
  - sudo apt-get install octave
  - sudo apt-get purge libopenblas-base # fixes PPA Octave 4.0 crash on Travis
script:
  - cd test && /usr/bin/octave -q --eval runMatlab2TikzTests.m
notifications:
  hipchat: f4c2c5f87adc85025545e5b59b3fbe@Matlab2tikz
