language: c++
# command to install dependencies
before_install:
  - sudo add-apt-repository -y ppa:octave/stable
  - sudo apt-get update -qq
  - sudo apt-get install octave
script:
  - cd test && ./runtests
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/eb74a6e982908d4ce209
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false